### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by byteschain** [zdyszm/coinaddress#1]
cc -O3 -g -std=gnu99 -W -Wextra -Wimplicit-function-declaration -Wredundant-decls -Wstrict-prototypes -Wundef -Wshadow -Wpointer-arith -Wformat -Wreturn-type -Wsign-compare -Wmultichar -Wformat-nonliteral -Winit-self -Wuninitialized -Wformat-security -Werror -I. -DVALGRIND=1 -DUSE_ETHEREUM=0 -DUSE_GRAPHENE=1 -DUSE_KECCAK=1 -DUSE_MONERO=0 -DUSE_NEM=1 -DUSE_CARDANO=1   -o coinaddress bignum.c ecdsa.c curves.c secp256k1.c nist256p1.c rand.c hmac.c bip32.c bip39.c bip32_bip39.c pbkdf2.c base58.c base32.c address.c script.c ripemd160.c sha2.c sha3.c hasher.c aes/aescrypt.c aes/aeskey.c aes/aestab.c aes/aes_modes.c ed25519-donna/curve25519-donna-32bit.c ed25519-donna/curve25519-donna-helpers.c ed25519-donna/modm-donna-32bit.c ed25519-donna/ed25519-donna-basepoint-table.c ed25519-donna/ed25519-donna-32bit-tables.c ed25519-donna/ed25519-donna-impl-base.c ed25519-donna/ed25519.c ed25519-donna/curve25519-donna-scalarmult-base.c ed25519-donna/ed25519-sha3.c ed25519-donna/ed25519-keccak.c blake256.c blake2b.c blake2s.c groestl.c nem.c memzero.c hexutils.c main.c
hmac.c: In function ‘pad_init’:
hmac.c:187:18: error: ‘MAX_DIGEST_BLOCK_LEN’ undeclared (first use in this function)
  for (i = 0; i < MAX_DIGEST_BLOCK_LEN && i < key_len; i++) {
                  ^
hmac.c:187:18: note: each undeclared identifier is reported only once for each function it appears in
hmac.c: In function ‘hmac_sha3_256’:
hmac.c:259:32: error: ‘MAX_DIGEST_BLOCK_LEN’ undeclared (first use in this function)
  unsigned char block_inner_pad[MAX_DIGEST_BLOCK_LEN] = { 0 };
                                ^
hmac.c: In function ‘hmac_sha3_512’:
hmac.c:306:32: error: ‘MAX_DIGEST_BLOCK_LEN’ undeclared (first use in this function)
  unsigned char block_inner_pad[MAX_DIGEST_BLOCK_LEN] = { 0 };
                                ^
make: *** [coinaddress] Error 1

**Comment by zdyszm** [comment]
please pull.thanks
